### PR TITLE
Adding workshop introduction slides

### PR DESCRIPTION
**Pull request by Jen-OMalley**
A first draft of the intro slides, as discussed in [**#824**](https://github.com/AlexsLemonade/training-admin/issues/824).

### CODE REVIEW

**Comment by Jen-OMalley** [comment]
I just noticed a typo in the last slide, in the line about waivers. Will fix this along with any other issues you may uncover, **@jashapiro**!

**Comment by Jen-OMalley** [comment]
Making note of the suggestions made [**in this issue**](https://github.com/AlexsLemonade/training-modules/issues/634).

**Comment by sjspielman** [comment]
Noting some comments I made over in another issue that I should have left here! https://github.com/AlexsLemonade/training-modules/issues/634#issue-1556727983

> I'm been looking through the intro to workshop slides that @Jen-OMalley put together (thanks!) and I'm realizing there are some small tweaks we probably need to make for this workshop. I made a couple small changes -
>   * all scRNA-Seq --> scRNA-seq (lowercase) in the slides
>   * hid the cheatsheets slide (feedback on this?)
>   * left a comment that we need a new screenshot for module structure! But the main thing we need to decide here is whether we want to place the reference `md` documents into the advanced folder. Then, we can get a new screenshot.

**Comment by jashapiro** [comment]
I updated a few of the slides, including a new screenshot, and making the colors consistent for instruction vs. presentations... that part was probably overkill, but it made me happy.

**Comment by sjspielman** [comment]
@jashapiro screenshot 👍

**Comment by Jen-OMalley** [comment]
**@jashapiro** just committed a new PDF version of the slides with all of the edits. 

Noting I had to do this a second time because the hidden slides were still showing up at first. That is now fixed.

**Review by jashapiro — APPROVED** [review]
LGTM!

**Pull request merged**
